name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ['main']

env:
  AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'FunctionApp1'
  DOTNET_VERSION: '8.0.x'
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Zip the Function App'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          zip -r FunctionApp1.zip .
          popd

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'FunctionApp1'
          include-hidden-files: true
          path: ${{ github.workspace }}/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

      # - name: Azure login
      #   uses: azure/login@v2
      #   with:
      #     creds: '{"clientId":"${{ env.AZURE_CLIENT_ID }}","clientSecret":"${{ env.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZURE_TENANT_ID }}"}'

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: 2.64.0
      #     inlineScript: |
      #       # az functionapp deployment source config-zip \
      #       #   --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
      #       #   --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
      #       #   --src ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/FunctionApp1.zip
      #       #   -- debug

      #       az functionapp app up --app-name ${{ env.AZURE_FUNCTIONAPP_NAME }}
